Commit box
r-Techsupport/hyde pull request #123
Opened 2024-07-18 23:43 UTC by TheKrol

Added a commit box with functionality
1) Changes cannot be pushed if none occurred
2) Box will destroy upon changing article
3) 500-character limit for commit message

2024-07-18 23:46 UTC, TheKrol commented
Fixes #122

2024-07-19 01:26 UTC, zleyyij requested changes

2024-07-19 01:26 UTC, zleyyij commented on frontend/src/lib/components/Editor.svelte
> +	let charCount = 500;
Prefer `const` over `let` if a value is never reassigned.

2024-07-19 01:26 UTC, zleyyij commented on frontend/src/lib/components/Editor.svelte
> +		await tick();
I don't believe the `await tick();` here has any effect because there's no code after it that involves state that would have changed during that tick

2024-07-19 01:26 UTC, zleyyij commented on frontend/src/lib/components/Editor.svelte
> +			<input type="text" id="commitMessage" placeholder="Enter your commit message here" bind:this={commitMessageInput} maxlength="500" on:input={updateCharCount}>
I don't believe the id here is needed, and if it is, it should be kebab-case, not camelCase

2024-07-19 01:26 UTC, zleyyij commented on frontend/src/lib/components/Editor.svelte
> +			charCountElement.textContent = `${charCount} characters remaining`;
Svelte is reactive enough you shouldn't need to manually update this, just use `{charCount} characters remaining` where you're displaying it and svelte will automatically rerender the element when `charCount` changes.

This means that you can get rid of that ID. Generally, in svelte and a lot of other frameworks, you shouldn't ever need to find yourself using IDs much, there's often a more idiomatic way to do the same thing

2024-07-19 01:26 UTC, zleyyij commented on frontend/src/lib/components/Editor.svelte
> +				<button id="cancelBtn" on:click={() => showCommitModal = false}>Deny</button>
these IDs aren't needed

2024-07-19 01:26 UTC, zleyyij commented on backend/src/handlers_prelude/doc.rs
> +        &final_commit_message,
This is a good way to do this

2024-07-22 03:34 UTC, merged