Add: build.ps1 Script with same functions as build.sh
r-Techsupport/hyde pull request #78
Opened 2024-06-27 16:53 UTC by Boxersteavee

2024-06-27 18:08 UTC, zleyyij requested changes

2024-06-27 18:08 UTC, zleyyij commented on build.ps1
> +cd frontend
Please prefer pure powershell
```suggestion
Set-Location frontend
```

2024-06-27 18:08 UTC, zleyyij commented on build.ps1
> +xcopy frontend\build target\web /s /e
This should preferably be done in powershell with `Move-Item` to keep things consistent.

2024-06-27 18:08 UTC, zleyyij commented on build.ps1
> +mkdir target\hyde
Same thing goes for all of this, please prefer native powershell commands over aliases or windows binaries

2024-06-27 18:18 UTC, Boxersteavee commented
I'll tweak and redo it properly with normal powershell later. I kinda rushed this and mostly copied from the bat file I made (that then didn't work because batch files are a bitch to make work)

2024-06-28 12:31 UTC, Boxersteavee commented
Ignore latest commit. Somehow the readme got removed?

2024-06-28 14:36 UTC, zleyyij approved these changes

2024-06-28 14:36 UTC, merged